In [1]:
import pandas as pd

In [2]:
csv_movies = pd.read_csv(r"C:\Users\ATEEQUE\Downloads\data set of madam .csv")

In [3]:
csv_movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [5]:
csv_movies.nlargest(10,"No_of_Votes")[["Series_Title","Genre","IMDB_Rating","No_of_Votes"]]

,Series_Title,Genre,IMDB_Rating,No_of_Votes
0,The Shawshank Redemption,Drama,9.3,2343110
2,The Dark Knight,Action,9.0,2303232
8,Inception,Action,8.8,2067042
9,Fight Club,Drama,8.8,1854740
6,Pulp Fiction,Crime,8.9,1826188
11,Forrest Gump,Drama,8.8,1809221
14,The Matrix,Action,8.7,1676426
10,The Lord of the Rings: The Fellowship of the Ring,Action,8.8,1661481
5,The Lord of the Rings: The Return of the King,Action,8.9,1642758
1,The Godfather,Crime,9.2,1620367